### ISSUE TITLE
Failed to set the same static IP address from DHCP

### ISSUE THREAD

**Issue by leiyu-bytedance** [openbmc/phosphor-networkd#38] opened 2021-04-08 05:00 UTC
When the BMC is configured to use DHCP, and it gets the IP address from DHCP, it will fail to set the same static IP address.

Steps to reproduce:
1. Set DHCP;
```
busctl set-property xyz.openbmc_project.Network "/xyz/openbmc_project/network/<eth>" "xyz.openbmc_project.Network.EthernetInterface" "DHCPEnabled" s "xyz.openbmc_project.Network.EthernetInterface.DHCPConf.both"
```
2. Wait and make sure the BMC gets the IP from DHCP;
3. Set static IP to the same IP address from the DHCP:
```
busctl set-property xyz.openbmc_project.Network "/xyz/openbmc_project/network/<eth>" "xyz.openbmc_project.Network.EthernetInterface" "DHCPEnabled" s "xyz.openbmc_project.Network.EthernetInterface.DHCPConf.none"
sleep 1
busctl call xyz.openbmc_project.Network /xyz/openbmc_project/network/<eth> xyz.openbmc_project.Network.IP.Create IP ssys "xyz.openbmc_project.Network.IP.Protocol.IPv6" "<ip>" 64 ""
sleep 1
busctl set-property xyz.openbmc_project.Network "/xyz/openbmc_project/network/config" "xyz.openbmc_project.Network.SystemConfiguration" "DefaultGateway6" s "<gateway-ip>"
```

The expected behavior is that the BMC gets the static IP address, and the config is written to the systemd-networkd config file.

But the actual behavior is, there is no static IP address set and there is no static IP address in the config file.

**Comment by leiyu-bytedance** [comment] 2021-04-08 05:05
The cause of the issue is in below code snippet in `EthernetInterface::writeConfigurationFile()`:
```c++
// Static IP addresses
for (const auto& addr : addrs)
{
    if (originIsManuallyAssigned(addr.second->origin()) &&
        !dhcpIsEnabled(addr.second->type()))
    {
        // Process all static addresses
        std::string address = addr.second->address() + "/" +
                              std::to_string(addr.second->prefixLength());

        // build the address entries. Do not use [Network] shortcuts to
        // insert address entries.
        stream << "[Address]\n";
        stream << "Address=" << address << "\n";
    }
}
```

At the time of `writeConfigurationFile()`, the IP address on the DBus is still DHCP, so the check of `originIsManuallyAssigned(addr.second->origin())` is false, and the address is ignored.

**Comment by LeeTroy** [comment] 2021-04-08 05:51
I've met the similar issue addressed in: https://lists.ozlabs.org/pipermail/openbmc/2019-April/015807.html

The root cause was here `emplace(ipaddress, /*cut here*/)`, the `emplace` will only construct and insert the item when the **key** is new. Since we have the same ipaddress here, the emplace doesn't make any change to the map.

Please refer to the following code snippet:
https://github.com/openbmc/phosphor-networkd/blob/983da5568c70a75d0c0c2c2d05ee8e497d6cd4f6/ethernet_interface.cpp#L313-L320

The workaround we had at the moment was search for the key, if it is existed then `erase` it before the `emplace`.

We didn't finish signing the CCLA at that time, so the patch was not missed to upstream.

**Comment by leiyu-bytedance** [comment] 2021-04-09 10:17
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-networkd/+/42049

**Closed** 2021-05-07 11:36 UTC
